# Site settings
title: Seongeun So
description: "Programming, Artificial Intelligence, Startup and Entrepreneurship"
url: "http://sungeuns.github.io"
author:
  name: "Seongeun So"
  url: "http://sungeuns.github.io"

# Build settings
baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: pretty
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
